### ISSUE TITLE
Very interesting!

### ISSUE THREAD

**Issue by ruurdadema** [fpeek/AES67#1]
Can you give some more info on what to expect? And when?

Which language do you intent to use?
Which libraries do you intent to use?
Do you intent to also implement this for platforms other than Raspberry PI?

BTW. I would be happy to contribute.

**Comment by fpeek** [comment]
Hi Ruurd,

This project intends to provide a very basic AES67/AES70 implementation for educational purposes. As you can see in the history, the idea emerged about 2 years ago but due to insufficient time/priority there's no code yet in this project. Therefore I can't answer your question on when to expect anything.

I intend to use C/C++, current libraries are [JUCE](https://github.com/WeAreROLI/JUCE), and [PTPD](https://github.com/ptpd/ptpd). There's a lot of research to be done on additional libraries that might fit in this project. Since JUCE is a cross-platform framework I intend to make this available as software-only on Linux/OSX/Windows as well.

Contribution will be highly appreciated !

kind regards,
Fred

**Comment by ruurdadema** [comment]
Nice! Thanks for your response.

Any idea of what license you're going to use?

**Comment by fpeek** [comment]
MIT, but may change if the libraries that will be used require another license.

**Comment by fpeek** [comment]
Added these Q&A to the [wiki](https://github.com/fpeek/boardwalk/wiki)
